name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Or your desired Python version

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Deploy to PythonAnywhere
        run: |
          pip install requests

          PYTHONANYWHERE_TOKEN="${{ secrets.API }}"
          USERNAME="${{ secrets.USERNAME }}"
          PROJECT_PATH="/home/${USERNAME}/ccse2" 
          WEB_APP_NAME="dinoexho.pythonanywhere.com" # Replace with your web app name (if applicable)

          # Create a ZIP archive of the repository
          zip -r deploy.zip * -x ".git*" ".github*"

          # Upload the ZIP file
          curl -X POST -H "Authorization: Token ${PYTHONANYWHERE_TOKEN}" -F "file=@deploy.zip" "https://www.pythonanywhere.com/api/v0/user/${USERNAME}/files/path${PROJECT_PATH}/"

          # Optional: Reload your web application (if you have one)
          if [ ! -z "${WEB_APP_NAME}" ]; then
            curl -X POST -H "Authorization: Token ${PYTHONANYWHERE_TOKEN}" "https://www.pythonanywhere.com/api/v0/user/${USERNAME}/webapps/${WEB_APP_NAME}/reload/"
          fi

          rm deploy.zip # Clean up the ZIP file
